# Generated by Django 4.2.4 on 2023-09-14 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='participants',
            field=models.ManyToManyField(related_name='ptns', to=settings.AUTH_USER_MODEL),
        ),
    ]
